sims-lab/CapCruncher

- .github/workflows/python-template.yml
- environment.yml
- testing.yml
Add pip to conda environment, so that `pip install -e .` installs the package in the conda environment
> Fix tests kra

- ccanalyser/pipeline/pipeline.py
- ccanalyser/visualise_statistics.ipynb
> Fix stats display

- docs/installing.rst
The current URL is broken. It points to a file that was renamed.
> Update URL to YAML file

- ccanalyser/cli/__init__.py
Plot option missing from ccanalyser pipeline
> Added missing plot option

- ccanalyser/pipeline/pipeline.py
Fixed a bug in downloading chromsizes. Now ensuring that the path specified exists or will try to download.
> Fix downloading chromsizes

- capcruncher/cli/__init__.py
- capcruncher/pipeline/pipeline.py
- capcruncher/utils.py
Fixes minor bug with:
- Checking presence of blacklist will error if config.yml not present.
- Warning on missing DRMAA interface now prints without traceback
- No verbosity for bed validity checking before starting pipeline
Also small back-end changes to P.PARAMS
> Fix pipeline startup bugs

- capcruncher/cli/alignments_annotate.py
- capcruncher/pipeline/pipeline.py
- capcruncher/tests/test_annotate.py
- capcruncher/tools/annotate.py
- capcruncher/tools/filter.py
- Corrects a bug when using a bed file with one interval
- Annotation of multiple files now run in parallel
> Improve annotation

- capcruncher/cli/reporters_count.py
Fixes issue #94. This should only be an issue with Tiled-C datasets which have considerably more reporters.
> Fixes bug with reporter counting on files with >2x106 slices

- capcruncher/pipeline/pipeline.py
> Use scale factor

- environment.yml
> Pinned bowtie2 to greater than 2.4.4

- capcruncher/tests/test_cli.py
- capcruncher/tests/test_pipeline.py
Current tests expect coolbox to be installed. This has been corrected by this PR.
> Adjust tests for optional plotting

- capcruncher/cli/fastq_split.py
- capcruncher/pipeline/pipeline.py
- config.yml
- tests/test_pipeline.py
Ensures that intermediate fastq files are removed by default and also collates fastq files after deduplication, trimming and flashing to reduce the number of partitions.
> feat(preprocessing): Reduced disk space required by fastq files

- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/python-template.yml
- capcruncher/cli/alignments_annotate.py
- capcruncher/cli/cli_alignments.py
- capcruncher/cli/fastq_split.py
- capcruncher/pipeline/make_report.py
- capcruncher/pipeline/pipeline.py
- config.yml
- setup.cfg
- tests/test_cli.py
- tests/test_pipeline.py
Reverts sims-lab/CapCruncher#153
> Revert "fix(alignment_filter): Prevent cluster errors due to lack of allocated memory."

- .github/workflows/python-template.yml
- capcruncher/tools/deduplicate.py
- capcruncher/tools/filter.py
- capcruncher/tools/storage.py
- config.yml
- testing.yml
- tests/test_cli.py
- tests/test_pipeline.py
- tests/test_slice_filtering.py
- Fixes all slices being removed in Tiled-C filtering.
- Fixes Tiled-C method statistics error due to updated pandas version.
> fix(filtering): Fixes Tiled-C filtering error due to typo in index specification for remove_dual_capture_fragments

- capcruncher/cli/alignments_annotate.py
- capcruncher/cli/cli_utilities.py
- capcruncher/cli/reporters_count.py
- capcruncher/cli/reporters_store.py
- capcruncher/pipeline/pipeline.py
- capcruncher/tools/annotate.py
- capcruncher/tools/count.py
- capcruncher/tools/io.py
- capcruncher/tools/plotting.py
- capcruncher/tools/storage.py
- environment.yml
- tests/test_annotate.py
- tests/test_cli.py
- tests/test_pipeline.py
- Fixed issues due to dependency updates
- Fixed annotation issues of BAM files due to the "sorted" option in pybedtools intersect
- Fixed reporter counting in batches
- Fixed reporters store merged function
- Fixed reporters store binned function
- Re-write of merging parquet files using pyarrow dataset instead of dask.
> Fixes issues with annotation, filtering, storage and plotting for Tiled-C data

- capcruncher/api/storage.py
- capcruncher/cli/cli_interactions.py
- capcruncher/cli/interactions_store.py
- capcruncher/pipeline/workflow/rules/pileup.smk
Cis reporters incorrectly reported for tiled-c data as viewpoint window excluded.
> fix: cis-and-trans stats

- capcruncher/pipeline/workflow/Snakefile
> fix: converted all viewpoint names to strings

- capcruncher/pipeline/workflow/rules/filter.smk
This is currently causing errors. Need a better long term solution.
> fix(pipeline): ignores viewpoint validation

- capcruncher/cli/genome_digest.py
- capcruncher/utils.py
Fixes polars import error when reading non autosomes
> Fix to sorting on chromosomes with non-integer names (e.g. 'X')

- capcruncher/pipeline/utils.py
Fixes off and on values not being converted to True/False
> fix(pipeline): Use recursion to format config dictionary

- capcruncher/pipeline/workflow/scripts/make_ucsc_hub.py
* Increased sample regex greed
* Taking the stem of the parent dir for norm
> fix(ucsc-hub): Correct errors when generating the "Replicates" composite track

- environment.yml
- requirements-minimal.txt
- requirements.txt
* Issue with snakemake caused by upgraded PuLP package. Setting to <2.8.0 for now to avoid error.
> fix(deps): PuLP<2.8.0

- capcruncher/pipeline/workflow/rules/qc.smk
- capcruncher/pipeline/workflow/scripts/fastqc_wrapper.py
> fix(pipeline): fastqc rule uses the wrapper script
